# Generated by Django 5.2.3 on 2025-06-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['-created_at']},
        ),
    ]
